### ISSUE TITLE
Type in README - should be JTS

### ISSUE THREAD

**Issue by dr-jts** [sizmek-public/rtree2d#26]
Looks like the README says "JTC" instead of JTS.

**Comment by plokhotnyuk** [comment]
Thanks, Martin!
Long live, JTS!

**Comment by dr-jts** [comment]
Thanks, @plokhotnyuk. It was nice to see JTS did reasonably well in the performance shootout (considering how old that code is, and that we didn't really put much effort into optimization).

A couple of questions for you (or anyone):

1. Any recommendations for making the JTS code faster?
2. Have you looked at Hilbert packing to see if it is more performant for loading and/or quering?

**Comment by dr-jts** [comment]
Thanks for the suggestions.  I'm hoping to rewrite the JT STRtree sometime soon, so will explore these ideas.
